### ISSUE TITLE
Java run bug report

### ISSUE THREAD

**Issue by sanjida3** [whatwg/fetch#692]
java.lang.NullPointerException: Attempt to get length of null array
	at cok.aa(PG)
	at ccv.a(PG)
	at com.a(PG)
	at jxg.a(PG)
	at con.run(PG)
	at gvc.run(Unknown Source)
	at hzy.run(PG)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
	at avv.run(PG)

**Comment by sanjida3** [comment]
Solution this Java lines
